# Generated by Django 4.2.6 on 2023-10-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
