# Generated by Django 4.2.6 on 2023-10-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_transcription_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='text',
            new_name='transcript',
        ),
    ]
