# Generated by Django 4.2.6 on 2023-11-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_text_transcription_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('data', models.TextField()),
            ],
        ),
    ]
